apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - erigon.yaml
  - lighthouse.yaml
  - otterscan.yaml
  - blockscout.yaml
  - hazmebeenscammed.yaml
  # clickhouse.yaml temporarily removed â€” will add back after operator installs CRDs
