apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - erigon.yaml
  - lighthouse.yaml
  - otterscan.yaml
  - blockscout.yaml
  - hazmebeenscammed.yaml
  - clickhouse.yaml
  - ethereum-etl.yaml
  - gateway.yaml
  - cluster-issuer.yaml
