apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - storage-classes.yaml
  - helm-repositories.yaml
  - default-nodepool.yaml
  - ethereum-nodepool.yaml
  - clickhouse-operator.yaml
  - nginx-gateway-fabric.yaml
  - cert-manager.yaml
  - gateway-api-crds.yaml
